blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog_pages.urls', namespace='blog'))
]

blog_pages/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name= 'blog_list'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name= "blog_detail"),
    path('create/', views.BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/update/', views.BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete/', views.BlogDeleteView.as_view(), name='blog_delete')
]

blog_pages/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

blog_pages/forms.py
from django.forms import ModelForm
from .models import Post

class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 'content', 'author', 'categories' 
        ]

blog_pages/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView,  UpdateView, DeleteView
from .models import Post
from .forms import PostCreateForm
from django.urls  import reverse_lazy

# Create your views here.
class BlogListView(ListView):
    model = Post
    queryset = Post.objects.all()
    template_name = "blog/list.html"
    context_object_name = 'blogs'

class BlogDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = "blog/task_detail.html"
    context_object_name = 'blogs'
   
class BlogCreateView(CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = "blog/task_create.html"
    success_url = reverse_lazy('blog:blog_list')

class BlogUpdateView(UpdateView):
    model = Post
    form_class = PostCreateForm
    template_name = "blog/task_update.html"
    success_url= reverse_lazy('blog:blog_list')

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog/task_delete.html'
    success_url= reverse_lazy('blog:blog_list')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Blog app </title>
</head>
<body>
    {% block content%}

    {%endblock%}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/list.html
{% extends 'base.html'%}
{% block content%}
{%for blogs in blogs%}
<div class="container">
    <h1>{{blogs.title}}</h1>
    <p>{{blogs.content}}</p>
    <h2>{{blogs.author}}</h2>
    <h3>{{blogs.pub_data}}</h3>
    <a href="{%url 'blog:blog_detail' blogs.id%}" class="btn btn-primary"> Details </a>
    <br>
    <br>
    <a href="{%url 'blog:blog_create'%}" class="btn btn-success"> Create </a>
    <a href="{%url 'blog:blog_update' blogs.id%}" class="btn btn-warning"> Update </a>
    <a href="{%url 'blog:blog_delete' blogs.id%}" class="btn btn-danger"> Delete </a>
    </div>
    <br>
    <hr>

{%endfor%}
    {%endblock%}

templates/blog/task_create.html
{% extends 'base.html'%}

{% block content%}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn-primary" type="submit">Submit</button>
</form>
{%endblock%}

templates/blog/task_delete.html
{% extends 'base.html'%}

{% block content%}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button class="btn-danger" type="submit">Delete</button>
</form>
{%endblock%}

templates/blog/task_detail.html
{%extends 'base.html'%}

{%block content%}
<div class="container">
    <h1>{{blogs.title}}</h1>
    <p>{{blogs.content}}</p>
    <h2>{{blogs.author}}</h2>
    <h3>{{blogs.pub_data}}</h3>
    <a href="{%url 'blog:blog_list'%}" class="btn btn-primary"> Back </a>
    <br>
    <br>

    <a href="{%url 'blog:blog_update' blogs.id%}" class="btn btn-warning"> Update </a>
    <a href="{%url 'blog:blog_delete' blogs.id%}" class="btn btn-danger"> Delete </a>
    </div>

{%endblock%}

templates/blog/task_update.html
{% extends 'base.html'%}

{% block content%}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn-primary" type="submit">Submit</button>
</form>
{%endblock%}